version: '3.9'

services:
  app:
    build: .
    container_name: nest_app
    ports:
      - '3000:3000'
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_NAME: reading_app
      JWT_SECRET: supersecret
    volumes:
      - .:/app
    command: npm run start:dev

  db:
    image: postgres:15
    container_name: postgres_db
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: reading_app
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
